name: CI Preview

on:
  push:
    branches: [ preview ]

concurrency:
  group: package-ui
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 21.x
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - name: Setup gulp
        run: npm install gulp-cli

      - name: Package UI
        run: gulp bundle

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ui-bundle
          path: build/ui-bundle.zip
          retention-days: 1

      - name: Push bundle
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add build/ui-bundle.zip
          git commit -am "Automated bundle"
          git push

      - name: Rebuild developers site
        uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PUBLIC_PAT_CICD4_PUBLIC }}
          repository: plentymarkets/plenty-developers-docs
          event-type: UIBundleUpdate4Preview
          client-payload: '{ "repository": "${{github.repository}}" }'
